### ISSUE TITLE
想问一下，你的样式/主题都是哪里找的？

### ISSUE THREAD

**Issue by x1ah** [WanliangWei/myblog#1]
rt, THX!

**Comment by WanliangWei** [comment]
搜索框在[Codepen](http://codepen.io/)找到的。当然css要自己改。借鉴了[他的文章容器式样](http://aljun.me/)。导航栏图标是用的阿里巴巴矢量图标。我不会js,只能做到这程度。想要好看的前端式样就去codepen找吧，别人代码吃透后再自己改式样，参数。希望能够帮到你。

**Comment by x1ah** [comment]
get, THX!
